name: medpar_outcomes_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy==1.25.1
  - pandas==2.0.3
  - xlrd=2.0.1
  - openpyxl=3.1.2
  - pyarrow=11.0.0
  - python-duckdb=0.8.1
  - pip=23.1.2
  - pip:
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - altair==5.0.1
    - ipykernel==6.24.0
    - snakemake==7.30.1
